use indexmap::{IndexMap, IndexSet};
use iso8601_timestamp::Timestamp;
use revolt_config::{config, FeaturesLimits};
use revolt_models::v0::{
    self, BulkMessageResponse, DataMessageSend, Embed, MessageAuthor, MessageFlags, MessageSort,
    MessageWebhook, PushNotification, ReplyIntent, SendableEmbed, Text,
};
use revolt_permissions::{calculate_channel_permissions, ChannelPermission, PermissionValue};
use revolt_result::{ErrorType, Result};
use std::time::SystemTime;
use std::{collections::HashSet, hash::RandomState};
use ulid::Ulid;
use validator::Validate;

use crate::{
    events::client::EventV1,
    util::{
        bulk_permissions::BulkDatabasePermissionQuery, idempotency::IdempotencyKey,
        permissions::DatabasePermissionQuery,
    },
    Channel, Database, Emoji, File, MessageInteraction, User, AMQP,
};

#[cfg(feature = "tasks")]
use crate::tasks::{self, ack::AckEvent};

auto_derived_partial!(
    /// Message
    pub struct Message {
        /// Unique Id
        #[serde(rename = "_id")]
        pub id: String,
        /// Unique value generated by client sending this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub nonce: Option<String>,
        /// Id of the channel this message was sent in
        pub channel: String,
        /// Id of the user or webhook that sent this message
        pub author: String,
        /// The webhook that sent this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub webhook: Option<MessageWebhook>,
        /// Message content
        #[serde(skip_serializing_if = "Option::is_none")]
        pub content: Option<String>,
        /// System message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub system: Option<SystemMessage>,
        /// Array of attachments
        #[serde(skip_serializing_if = "Option::is_none")]
        pub attachments: Option<Vec<File>>,
        /// Time at which this message was last edited
        #[serde(skip_serializing_if = "Option::is_none")]
        pub edited: Option<Timestamp>,
        /// Attached embeds to this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub embeds: Option<Vec<Embed>>,
        /// Array of user ids mentioned in this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mentions: Option<Vec<String>>,
        /// Array of role ids mentioned in this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub role_mentions: Option<Vec<String>>,
        /// Array of message ids this message is replying to
        #[serde(skip_serializing_if = "Option::is_none")]
        pub replies: Option<Vec<String>>,
        /// Hashmap of emoji IDs to array of user IDs
        #[serde(skip_serializing_if = "IndexMap::is_empty", default)]
        pub reactions: IndexMap<String, IndexSet<String>>,
        /// Information about how this message should be interacted with
        #[serde(skip_serializing_if = "Interactions::is_default", default)]
        pub interactions: Interactions,
        /// Name and / or avatar overrides for this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub masquerade: Option<Masquerade>,
        /// Whether or not the message in pinned
        #[serde(skip_serializing_if = "crate::if_option_false")]
        pub pinned: Option<bool>,

        /// Id of the thread that was created from this message
        ///
        /// This is server-set only and never accepted from clients.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub thread_id: Option<String>,

        /// Interaction context when this message is a bot's response to a
        /// slash command ("used /cmd").
        ///
        /// Server-set only (by the interaction respond route); the regular
        /// send path never accepts it. NOT the `interactions`
        /// (reaction-guidance) field above.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub command_context: Option<MessageInteraction>,

        /// Interactive components attached to this message (buttons /
        /// selects). Bot authors only — the send path rejects components
        /// from regular users and webhooks.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub components: Option<Vec<v0::ActionRow>>,

        /// Sticker IDs attached to this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sticker_ids: Option<Vec<String>>,

        /// Immutable poll definition when this message carries a poll.
        /// Server-set only (by the poll create route); the regular send
        /// path never accepts it. Mutable poll state lives in `polls`.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub poll: Option<v0::PollDefinition>,

        /// Immutable soft-reserve sheet definition when this message
        /// carries one. Server-set only (by the soft-res create route);
        /// the regular send path never accepts it. Mutable sheet state
        /// lives in `softres_sheets`.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub softres: Option<v0::SoftResDefinition>,

        /// Immutable snapshot of another message this message forwards.
        /// Server-set only (by the forward route, which verifies read
        /// access on the source) — absent from `DataMessageSend` and
        /// `DataEditMessage`, so send/edit paths can never touch it.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub forwarded: Option<ForwardedSnapshot>,

        /// Server-set attribution on a delivered crosspost copy (origin
        /// message/channel/server ids). Set only by the crosspost route;
        /// the regular send path never accepts it.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub crosspost: Option<v0::CrosspostInfo>,

        /// Bitfield of message flags
        #[serde(skip_serializing_if = "Option::is_none")]
        pub flags: Option<u32>,
    },
    "PartialMessage"
);

auto_derived!(
    /// System Event
    #[serde(tag = "type")]
    pub enum SystemMessage {
        #[serde(rename = "text")]
        Text { content: String },
        #[serde(rename = "user_added")]
        UserAdded { id: String, by: String },
        #[serde(rename = "user_remove")]
        UserRemove { id: String, by: String },
        #[serde(rename = "user_joined")]
        UserJoined { id: String },
        #[serde(rename = "user_left")]
        UserLeft { id: String },
        #[serde(rename = "user_kicked")]
        UserKicked { id: String },
        #[serde(rename = "user_banned")]
        UserBanned { id: String },
        #[serde(rename = "channel_renamed")]
        ChannelRenamed { name: String, by: String },
        #[serde(rename = "channel_description_changed")]
        ChannelDescriptionChanged { by: String },
        #[serde(rename = "channel_icon_changed")]
        ChannelIconChanged { by: String },
        #[serde(rename = "channel_ownership_changed")]
        ChannelOwnershipChanged { from: String, to: String },
        #[serde(rename = "message_pinned")]
        MessagePinned { id: String, by: String },
        #[serde(rename = "message_unpinned")]
        MessageUnpinned { id: String, by: String },
        #[serde(rename = "call_started")]
        CallStarted {
            by: String,
            finished_at: Option<Timestamp>,
        },
        #[serde(rename = "thread_created")]
        ThreadCreated {
            id: String,
            by: String,
            name: String,
        },
        #[serde(rename = "call_recording_started")]
        CallRecordingStarted { by: String },
        #[serde(rename = "call_recording_stopped")]
        CallRecordingStopped { by: String },
    }

    /// Name and / or avatar override information
    pub struct Masquerade {
        /// Replace the display name shown on this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: Option<String>,
        /// Replace the avatar shown on this message (URL to image file)
        #[serde(skip_serializing_if = "Option::is_none")]
        pub avatar: Option<String>,
        /// Replace the display role colour shown on this message
        ///
        /// Must have `ManageRole` permission to use
        #[serde(skip_serializing_if = "Option::is_none")]
        pub colour: Option<String>,
    }

    /// Information to guide interactions on this message
    #[derive(Default)]
    pub struct Interactions {
        /// Reactions which should always appear and be distinct
        #[serde(skip_serializing_if = "Option::is_none", default)]
        pub reactions: Option<IndexSet<String>>,
        /// Whether reactions should be restricted to the given list
        ///
        /// Can only be set to true if reactions list is of at least length 1
        #[serde(skip_serializing_if = "crate::if_false", default)]
        pub restrict_reactions: bool,
    }

    /// Appended Information
    pub struct AppendMessage {
        /// Additional embeds to include in this message
        #[serde(skip_serializing_if = "Option::is_none")]
        pub embeds: Option<Vec<Embed>>,
    }

    /// Message Time Period
    ///
    /// Filter and sort messages by time
    #[serde(untagged)]
    pub enum MessageTimePeriod {
        Relative {
            /// Message id to search around
            ///
            /// Specifying 'nearby' ignores 'before', 'after' and 'sort'.
            /// It will also take half of limit rounded as the limits to each side.
            /// It also fetches the message ID specified.
            nearby: String,
        },
        Absolute {
            /// Message id before which messages should be fetched
            before: Option<String>,
            /// Message id after which messages should be fetched
            after: Option<String>,
            /// Message sort direction
            sort: Option<MessageSort>,
        },
    }

    /// Message Filter
    #[derive(Default)]
    pub struct MessageFilter {
        /// Parent channel ID
        pub channel: Option<String>,
        /// Message author ID
        pub author: Option<String>,
        /// Search query
        pub query: Option<String>,
        /// Search for pinned
        pub pinned: Option<bool>,
    }

    /// Message Query
    pub struct MessageQuery {
        /// Maximum number of messages to fetch
        ///
        /// For fetching nearby messages, this is \`(limit + 1)\`.
        pub limit: Option<i64>,
        /// Filter to apply
        #[serde(flatten)]
        pub filter: MessageFilter,
        /// Time period to fetch
        #[serde(flatten)]
        pub time_period: MessageTimePeriod,
    }

    /// Optional fields on message
    pub enum FieldsMessage {
        Pinned,
        /// Component rows removed (a component edit-response with an empty
        /// array clears the message's components)
        Components,
    }

    /// Immutable, server-copied snapshot of a forwarded message.
    ///
    /// The attachments here are freshly-minted `File` documents owned by
    /// the FORWARDING message (hash refcounting keeps the underlying object
    /// alive while either side references it).
    pub struct ForwardedSnapshot {
        /// Id of the original message
        pub message_id: String,
        /// Id of the channel the original message was sent in
        pub channel_id: String,
        /// Id of the server the original channel belongs to, if any
        #[serde(skip_serializing_if = "Option::is_none")]
        pub server_id: Option<String>,
        /// Id of the original author (None when sent by a webhook)
        #[serde(skip_serializing_if = "Option::is_none")]
        pub author_id: Option<String>,
        /// Content of the original message at forward time
        #[serde(skip_serializing_if = "Option::is_none")]
        pub content: Option<String>,
        /// Copies of the original attachments
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub attachments: Vec<File>,
        /// When the original message was sent (ms since epoch, UTC)
        pub original_sent_at: i64,
    }
);

/// Stored mask for `MessageFlags::SuppressNotifications`.
///
/// This is the one flag stored as a MASK and not at the bit position its
/// discriminant names (that would be bit 1, value 2). Clients send
/// `flags |= 1` for a silent message and read it back as `flags & 1`, and the
/// protected-channel flag allowlist accepts exactly 0 or 1. Every other flag is
/// a bit position (`1 << flag`). `MessageFlagsValue::has`/`set` route
/// `SuppressNotifications` here, so callers never see the difference.
const SUPPRESS_NOTIFICATIONS_MASK: u32 = 1;

pub struct MessageFlagsValue(pub u32);

impl MessageFlagsValue {
    pub fn has(&self, flag: MessageFlags) -> bool {
        match flag {
            MessageFlags::SuppressNotifications => {
                self.0 & SUPPRESS_NOTIFICATIONS_MASK == SUPPRESS_NOTIFICATIONS_MASK
            }
            flag => self.has_value(flag as u32),
        }
    }
    pub fn has_value(&self, bit: u32) -> bool {
        let mask = 1 << bit;
        self.0 & mask == mask
    }

    pub fn set(&mut self, flag: MessageFlags, toggle: bool) -> &mut Self {
        match flag {
            MessageFlags::SuppressNotifications => {
                if toggle {
                    self.0 |= SUPPRESS_NOTIFICATIONS_MASK;
                } else {
                    self.0 &= !SUPPRESS_NOTIFICATIONS_MASK;
                }
                self
            }
            flag => self.set_value(flag as u32, toggle),
        }
    }
    pub fn set_value(&mut self, bit: u32, toggle: bool) -> &mut Self {
        if toggle {
            self.0 |= 1 << bit;
        } else {
            self.0 &= !(1 << bit);
        }
        self
    }
}

#[allow(clippy::derivable_impls)]
impl Default for Message {
    fn default() -> Self {
        Self {
            id: Default::default(),
            nonce: None,
            channel: Default::default(),
            author: Default::default(),
            webhook: None,
            content: None,
            system: None,
            attachments: None,
            edited: None,
            embeds: None,
            mentions: None,
            role_mentions: None,
            replies: None,
            reactions: Default::default(),
            interactions: Default::default(),
            masquerade: None,
            flags: None,
            pinned: None,
            thread_id: None,
            command_context: None,
            components: None,
            sticker_ids: None,
            poll: None,
            softres: None,
            forwarded: None,
            crosspost: None,
        }
    }
}

#[allow(clippy::disallowed_methods)]
impl Message {
    /// Create message from API data
    #[allow(clippy::too_many_arguments)]
    pub async fn create_from_api(
        db: &Database,
        amqp: Option<&AMQP>,
        channel: Channel,
        data: DataMessageSend,
        author: MessageAuthor<'_>,
        user: Option<v0::User>,
        member: Option<v0::Member>,
        limits: FeaturesLimits,
        idempotency: IdempotencyKey,
        generate_embeds: bool,
        allow_mentions: bool,
    ) -> Result<Message> {
        Message::create_from_api_with_id(
            db,
            amqp,
            channel,
            data,
            author,
            user,
            member,
            limits,
            idempotency,
            generate_embeds,
            allow_mentions,
            None,
            None,
            true,
        )
        .await
    }

    /// Create message from API data, optionally forcing the message id.
    ///
    /// Forum post creation pins the starter message's id to the post's
    /// (thread's) id so starters can be bulk-fetched by id when listing
    /// posts. Every other caller passes `None` and gets a fresh ulid.
    ///
    /// `resolved_attachments`, when `Some`, replaces the normal
    /// claim-by-id attachment path: the given `File` rows are attached
    /// verbatim and `data.attachments` is ignored. The scheduled-message
    /// daemon uses this — its attachments were already claimed (against
    /// the scheduled row) at schedule time, so `File::use_attachment`
    /// (which only matches unclaimed files) would 404 on them.
    ///
    /// `ack_author` is forwarded to [`Message::send_with_ack_author`]:
    /// whether sending also marks the channel read for its (user) author.
    /// Interactive callers pass `true`; the scheduled-message daemon passes
    /// a computed value, since the author is not present at delivery.
    #[allow(clippy::too_many_arguments)]
    pub async fn create_from_api_with_id(
        db: &Database,
        amqp: Option<&AMQP>,
        channel: Channel,
        data: DataMessageSend,
        author: MessageAuthor<'_>,
        user: Option<v0::User>,
        member: Option<v0::Member>,
        limits: FeaturesLimits,
        mut idempotency: IdempotencyKey,
        generate_embeds: bool,
        allow_mentions: bool,
        forced_id: Option<String>,
        resolved_attachments: Option<Vec<File>>,
        ack_author: bool,
    ) -> Result<Message> {
        let config = config().await;

        Message::validate_sum(
            &data.content,
            data.embeds.as_deref().unwrap_or_default(),
            limits.message_length,
        )?;

        idempotency
            .consume_nonce(data.nonce)
            .await
            .map_err(|_| create_error!(InvalidOperation))?;

        // Check the message is not empty
        if (data.content.as_ref().is_none_or(|v| v.is_empty()))
            && (data.attachments.as_ref().is_none_or(|v| v.is_empty()))
            && (data.embeds.as_ref().is_none_or(|v| v.is_empty()))
            && (data.sticker_ids.as_ref().is_none_or(|v| v.is_empty()))
        {
            return Err(create_error!(EmptyMessage));
        }

        let allow_mass_mentions = allow_mentions && config.features.mass_mentions_enabled;

        let mut mentions_everyone = false;
        let mut mentions_online = false;
        let mut suppress_notifications = false;

        if let Some(raw_flags) = &data.flags {
            if raw_flags > &7 {
                // quick path to failure: bigger than all the bits combined
                return Err(create_error!(InvalidProperty));
            }

            // First step of mass mention resolution
            let flags = MessageFlagsValue(*raw_flags);
            suppress_notifications = flags.has(MessageFlags::SuppressNotifications);
            mentions_everyone = allow_mentions && flags.has(MessageFlags::MentionsEveryone);
            mentions_online = allow_mentions && flags.has(MessageFlags::MentionsOnline);

            // Not a bot, and attempting to set mention flags
            if user.as_ref().is_some_and(|u| u.bot.as_ref().is_none())
                && (mentions_everyone || mentions_online)
            {
                return Err(create_error!(IsNotBot));
            }

            if mentions_everyone && mentions_online {
                return Err(create_error!(InvalidFlagValue));
            }
        }

        let server_id = match channel {
            Channel::TextChannel { ref server, .. }
            | Channel::Thread { ref server, .. }
            | Channel::Forum { ref server, .. } => Some(server.clone()),
            _ => None,
        };

        // Components are bot-only: regular users, webhooks and system
        // messages cannot attach them (interaction fan-out must always
        // resolve to a live bot session).
        if let Some(components) = &data.components {
            if user.as_ref().is_none_or(|u| u.bot.is_none()) {
                return Err(create_error!(IsNotBot));
            }

            v0::ActionRow::validate_structure(components)
                .map_err(|error| create_error!(FailedValidation { error }))?;
        }

        // Ensure restrict_reactions is not specified without reactions list
        if let Some(interactions) = &data.interactions {
            if interactions.restrict_reactions {
                let disallowed = if let Some(list) = &interactions.reactions {
                    list.is_empty()
                } else {
                    true
                };

                if disallowed {
                    return Err(create_error!(InvalidProperty));
                }
            }
        }

        let (author_id, webhook) = match &author {
            MessageAuthor::User(user) => (user.id.clone(), None),
            MessageAuthor::Webhook(webhook) => (webhook.id.clone(), Some((*webhook).clone())),
            MessageAuthor::System { .. } => ("00000000000000000000000000".to_string(), None),
        };

        // Start constructing the message
        let message_id = forced_id.unwrap_or_else(|| Ulid::new().to_string());
        let mut message = Message {
            id: message_id.clone(),
            channel: channel.id().to_string(),
            masquerade: data.masquerade.map(|masquerade| masquerade.into()),
            interactions: data
                .interactions
                .map(|interactions| interactions.into())
                .unwrap_or_default(),
            author: author_id,
            webhook: webhook.map(|w| w.into()),
            flags: data.flags,
            components: data.components,
            ..Default::default()
        };

        // Parse mentions in message.

        let mut message_mentions = if let Some(raw_content) = &data.content {
            revolt_parser::parse_message(raw_content)
        } else {
            revolt_parser::MessageResults::default()
        };

        message_mentions.mentions_everyone |= mentions_everyone;
        message_mentions.mentions_online |= mentions_online;

        let revolt_parser::MessageResults {
            mut user_mentions,
            mut role_mentions,
            mut mentions_everyone,
            mut mentions_online,
            ..
        } = message_mentions;

        if allow_mass_mentions && server_id.is_some() && !role_mentions.is_empty() {
            let server_data = db
                .fetch_server(server_id.unwrap().as_str())
                .await
                .expect("Failed to fetch server");

            role_mentions.retain(|role_id| server_data.roles.contains_key(role_id));
        }

        // Validate the user can perform a mass mention
        if !config.features.mass_mentions_enabled
            && (mentions_everyone || mentions_online || !role_mentions.is_empty())
        {
            mentions_everyone = false;
            mentions_online = false;
            role_mentions.clear();
        } else if mentions_everyone || mentions_online || !role_mentions.is_empty() {
            debug!(
                "Mentioned everyone: {}, mentioned online: {}, mentioned roles: {:?}",
                mentions_everyone, mentions_online, &role_mentions
            );
            if let Some(user) = match author {
                MessageAuthor::User(user) => Some(Ok(user)),
                MessageAuthor::System { .. } => Some(Err(())), // DISALLOWED
                MessageAuthor::Webhook(..) => None,            // Bypass check
            } {
                if user.is_err() {
                    return Err(create_error!(InvalidProperty));
                }
                let owned_user: User = user.unwrap().to_owned().into();

                // Threads delegate permissions to their parent text channel.
                let permission_channel = channel.permission_target(db).await?;
                let mut query =
                    DatabasePermissionQuery::new(db, &owned_user).channel(&permission_channel);
                let perms = calculate_channel_permissions(&mut query).await;

                if (mentions_everyone || mentions_online)
                    && !perms.has_channel_permission(ChannelPermission::MentionEveryone)
                {
                    return Err(create_error!(MissingPermission {
                        permission: ChannelPermission::MentionEveryone.to_string()
                    }));
                }

                if !role_mentions.is_empty()
                    && !perms.has_channel_permission(ChannelPermission::MentionRoles)
                {
                    return Err(create_error!(MissingPermission {
                        permission: ChannelPermission::MentionRoles.to_string()
                    }));
                }
            }
        }

        // Verify replies are valid.
        let mut replies = Vec::new();

        if let Some(entries) = data.replies {
            if entries.len() > config.features.limits.global.message_replies {
                return Err(create_error!(TooManyReplies {
                    max: config.features.limits.global.message_replies,
                }));
            }

            replies.reserve(entries.len());

            for ReplyIntent {
                id,
                mention,
                fail_if_not_exists,
            } in entries
            {
                match db.fetch_message(&id).await {
                    // Referenced message exists
                    Ok(message) => {
                        if mention && allow_mentions {
                            user_mentions.insert(message.author.to_owned());
                        }

                        // This is O(n^2), but this is faster than a HashSet
                        // when n < 20; as long as the message_replies limit
                        // is reasonable, this will be fast.
                        if !replies.contains(&message.id) {
                            replies.push(message.id);
                        }
                    }
                    // If the referenced message doesn't exist and fail_if_not_exists
                    // is set to false, send the message without the reply.
                    Err(e) => {
                        if !matches!(e.error_type, ErrorType::NotFound)
                            || fail_if_not_exists.unwrap_or(true)
                        {
                            return Err(e);
                        }
                    }
                }
            }
        }

        // Validate the mentions go to users in the channel/server
        if !user_mentions.is_empty() {
            #[allow(deprecated)]
            match channel {
                Channel::DirectMessage { ref recipients, .. }
                | Channel::Group { ref recipients, .. } => {
                    let recipients_hash = HashSet::<&String, RandomState>::from_iter(recipients);
                    user_mentions.retain(|m| recipients_hash.contains(m));
                    role_mentions.clear();
                }
                Channel::TextChannel { ref server, .. }
                | Channel::Thread { ref server, .. }
                | Channel::Forum { ref server, .. } => {
                    let mentions_vec = Vec::from_iter(user_mentions.iter().cloned());

                    let valid_members = db.fetch_members(server.as_str(), &mentions_vec[..]).await;
                    if let Ok(valid_members) = valid_members {
                        let valid_mentions = HashSet::<&String, RandomState>::from_iter(
                            valid_members.iter().map(|m| &m.id.user),
                        );

                        user_mentions.retain(|m| valid_mentions.contains(m)); // quick pass, validate mentions are in the server

                        if !user_mentions.is_empty() {
                            // if there are still mentions, drill down to a channel-level
                            // (threads evaluate visibility against their parent's overrides)
                            let permission_channel = channel.permission_target(db).await?;
                            let member_channel_view_perms =
                                BulkDatabasePermissionQuery::from_server_id(db, server)
                                    .await
                                    .channel(&permission_channel)
                                    .members(&valid_members)
                                    .members_can_see_channel()
                                    .await;

                            user_mentions
                                .retain(|m| *member_channel_view_perms.get(m).unwrap_or(&false));
                        }
                    } else {
                        revolt_config::capture_error(&valid_members.unwrap_err());
                        return Err(create_error!(InternalError));
                    }
                }
                Channel::SavedMessages { .. } => {
                    user_mentions.clear();
                }
            }
        }

        if !user_mentions.is_empty() {
            message
                .mentions
                .replace(user_mentions.into_iter().collect());
        }

        if !role_mentions.is_empty() {
            message
                .role_mentions
                .replace(role_mentions.into_iter().collect());
        }

        if !replies.is_empty() {
            message.replies.replace(replies);
        }

        // Calculate final message flags
        let mut flag_value = MessageFlagsValue(0);
        flag_value
            .set(MessageFlags::SuppressNotifications, suppress_notifications)
            .set(MessageFlags::MentionsEveryone, mentions_everyone)
            .set(MessageFlags::MentionsOnline, mentions_online);

        message.flags = Some(flag_value.0);

        // Add attachments to message.
        let mut attachments = vec![];
        if data
            .attachments
            .as_ref()
            .is_some_and(|v| v.len() > limits.message_attachments)
        {
            return Err(create_error!(TooManyAttachments {
                max: limits.message_attachments,
            }));
        }

        if data
            .embeds
            .as_ref()
            .is_some_and(|v| v.len() > config.features.limits.global.message_embeds)
        {
            return Err(create_error!(TooManyEmbeds {
                max: config.features.limits.global.message_embeds,
            }));
        }

        if let Some(resolved) = resolved_attachments {
            // Pre-resolved files (scheduled delivery): already claimed at
            // schedule time and retargeted to this message by the caller.
            attachments.extend(resolved);
        } else {
            for attachment_id in data.attachments.as_deref().unwrap_or_default() {
                attachments
                    .push(File::use_attachment(db, attachment_id, &message_id, author.id()).await?);
            }
        }

        if !attachments.is_empty() {
            message.attachments.replace(attachments);
        }

        // Process included embeds.
        for sendable_embed in data.embeds.unwrap_or_default() {
            message.attach_sendable_embed(db, sendable_embed).await?;
        }

        // Set content
        message.content = data.content;

        // Set sticker IDs
        if let Some(sticker_ids) = data.sticker_ids {
            if !sticker_ids.is_empty() {
                message.sticker_ids = Some(sticker_ids);
            }
        }

        // Pass-through nonce value for clients
        message.nonce = Some(idempotency.into_key());

        // Send the message
        message
            .send_with_ack_author(
                db,
                amqp,
                author,
                user,
                member,
                &channel,
                generate_embeds,
                ack_author,
            )
            .await?;

        Ok(message)
    }

    /// Send a message without any notifications
    pub async fn send_without_notifications(
        &mut self,
        db: &Database,
        user: Option<v0::User>,
        member: Option<v0::Member>,
        is_dm: bool,
        generate_embeds: bool,
        // This determines if this function should queue the mentions task or if somewhere else will.
        // If this is true, you MUST call tasks::ack::queue yourself.
        mentions_elsewhere: bool,
    ) -> Result<()> {
        db.insert_message(self).await?;

        // Fan out events
        EventV1::Message(self.clone().into_model(user, member))
            .p(self.channel.to_string())
            .await;

        // Update last_message_id
        #[cfg(feature = "tasks")]
        tasks::last_message_id::queue(self.channel.to_string(), self.id.to_string(), is_dm).await;

        // Add mentions for affected users
        #[cfg(feature = "tasks")]
        if !mentions_elsewhere {
            if let Some(mentions) = &self.mentions {
                tasks::ack::queue_message(
                    self.channel.to_string(),
                    AckEvent::ProcessMessage {
                        messages: vec![(
                            None,
                            self.clone(),
                            mentions.clone(),
                            self.has_suppressed_notifications(),
                        )],
                    },
                )
                .await;
            }
        }

        // Generate embeds
        #[cfg(feature = "tasks")]
        if generate_embeds {
            if let Some(content) = &self.content {
                tasks::process_embeds::queue(
                    self.channel.to_string(),
                    self.id.to_string(),
                    content.clone(),
                )
                .await;
            }
        }

        Ok(())
    }

    /// Send a message
    ///
    /// Marks the channel read for a (non-bot) user author; see
    /// [`Message::send_with_ack_author`].
    #[allow(clippy::too_many_arguments)]
    pub async fn send(
        &mut self,
        db: &Database,
        amqp: Option<&AMQP>, // this is optional mostly for tests.
        author: MessageAuthor<'_>,
        user: Option<v0::User>,
        member: Option<v0::Member>,
        channel: &Channel,
        generate_embeds: bool,
    ) -> Result<()> {
        self.send_with_ack_author(
            db,
            amqp,
            author,
            user,
            member,
            channel,
            generate_embeds,
            true,
        )
        .await
    }

    /// Send a message, choosing whether to mark the channel read for its author
    ///
    /// With `ack_author`, a non-bot user author gets a `ChannelAck` for this
    /// message (needs `amqp`). [`Message::send`] always passes `true`; the
    /// scheduled-message daemon passes a computed value, because the author is
    /// absent at delivery and an unconditional ack could mark messages they
    /// never saw as read.
    #[allow(clippy::too_many_arguments)]
    pub async fn send_with_ack_author(
        &mut self,
        db: &Database,
        amqp: Option<&AMQP>, // this is optional mostly for tests.
        author: MessageAuthor<'_>,
        user: Option<v0::User>,
        member: Option<v0::Member>,
        channel: &Channel,
        generate_embeds: bool,
        ack_author: bool,
    ) -> Result<()> {
        self.send_without_notifications(
            db,
            user.clone(),
            member.clone(),
            matches!(channel, Channel::DirectMessage { .. }),
            generate_embeds,
            true,
        )
        .await?;

        // Sending marks the channel read for its author, so their other
        // sessions and the next cold load agree. Webhooks and system
        // messages are excluded by the match, bots by the check below.
        // Best-effort: the message is already stored and fanned out.
        if ack_author {
            if let (Some(amqp), MessageAuthor::User(u)) = (amqp, &author) {
                if u.bot.is_none() {
                    if let Err(e) = channel.ack(&u.id, &self.id, amqp).await {
                        revolt_config::capture_error(&e);
                    }
                }
            }
        }

        let is_dm_or_group = matches!(
            channel,
            Channel::DirectMessage { .. } | Channel::Group { .. }
        );
        // Threads push like DMs: every joined member is a notification target,
        // not just mentioned users.
        let is_thread = matches!(channel, Channel::Thread { .. });

        // A silent message still takes this branch, marked `silenced`: the ack
        // task records its mentions and unreads (`send_without_notifications`
        // was told to leave that to us) and only skips the push.
        if is_dm_or_group
            || is_thread
            || self.mentions.is_some()
            || self.contains_mass_push_mention()
        {
            // send Push notifications
            #[cfg(feature = "tasks")]
            {
                let recipients: Vec<String> = match channel {
                    Channel::DirectMessage { recipients, .. }
                    | Channel::Group { recipients, .. } => recipients
                        .iter()
                        .filter(|uid| *uid != author.id())
                        .cloned()
                        .collect(),
                    // Joined thread members (minus the author) receive DM-style
                    // push; the ack task applies each recipient's mute settings.
                    // Explicitly-mentioned users are unioned in so a mention
                    // still notifies even if they have not joined the thread.
                    // Restricted to current server members; see the helper.
                    Channel::Thread { server, .. } => {
                        thread_push_recipients(
                            db,
                            server,
                            &self.channel,
                            author.id(),
                            self.mentions.as_deref(),
                        )
                        .await
                    }
                    // Never notify the author of their own message (self-mention
                    // or reply-ping of their own message).
                    Channel::TextChannel { .. } => self
                        .mentions
                        .iter()
                        .flatten()
                        .filter(|uid| uid.as_str() != author.id())
                        .cloned()
                        .collect(),
                    _ => vec![],
                };

                // Queue when there is a concrete recipient OR the message is a
                // mass mention — mass mentions have no explicit recipients but
                // must still reach the ack worker, which fans them out to the
                // server (mirrors the worker's own rejection predicate).
                if !recipients.is_empty() || self.contains_mass_push_mention() {
                    tasks::ack::queue_message(
                        self.channel.to_string(),
                        AckEvent::ProcessMessage {
                            messages: vec![(
                                Some(
                                    PushNotification::from(
                                        self.clone().into_model(user, member),
                                        Some(author.clone()),
                                        channel.to_owned().into(),
                                    )
                                    .await,
                                ),
                                self.clone(),
                                recipients,
                                self.has_suppressed_notifications(),
                            )],
                        },
                    )
                    .await;
                }
            }
        }

        Ok(())
    }

    /// Create text embed from sendable embed
    pub async fn create_embed(&self, db: &Database, embed: SendableEmbed) -> Result<Embed> {
        embed.validate().map_err(|error| {
            create_error!(FailedValidation {
                error: error.to_string()
            })
        })?;

        let media = if let Some(id) = embed.media {
            Some(File::use_attachment(db, &id, &self.id, &self.author).await?)
        } else {
            None
        };

        Ok(Embed::Text(Text {
            icon_url: embed.icon_url,
            url: embed.url,
            title: embed.title,
            description: embed.description,
            media: media.map(|m| m.into()),
            colour: embed.colour,
        }))
    }

    /// Whether this message has suppressed notifications
    pub fn has_suppressed_notifications(&self) -> bool {
        self.flags
            .is_some_and(|flags| MessageFlagsValue(flags).has(MessageFlags::SuppressNotifications))
    }

    pub fn contains_mass_push_mention(&self) -> bool {
        let ping = if let Some(flags) = self.flags {
            let flags = MessageFlagsValue(flags);
            flags.has(MessageFlags::MentionsEveryone)
        } else {
            false
        };

        ping || self.role_mentions.is_some()
    }

    /// Update message data
    pub async fn update(
        &mut self,
        db: &Database,
        partial: PartialMessage,
        remove: Vec<FieldsMessage>,
    ) -> Result<()> {
        self.apply_options(partial.clone());

        for field in &remove {
            self.remove_field(field);
        }

        db.update_message(&self.id, &partial, remove.clone())
            .await?;

        EventV1::MessageUpdate {
            id: self.id.clone(),
            channel: self.channel.clone(),
            data: partial.into(),
            clear: remove.into_iter().map(|field| field.into()).collect(),
        }
        .p(self.channel.clone())
        .await;

        Ok(())
    }

    /// User ids to fetch alongside these messages: the `author` of every message
    /// and the users named by system messages, deduplicated in no particular order.
    ///
    /// `author` is taken as-is, so a webhook-authored message contributes its
    /// webhook id and a system message contributes the all-zero system author;
    /// callers that must not look those up filter the messages first. Mentions,
    /// replies and forwarded authors are not included.
    pub fn referenced_user_ids(messages: &[Message]) -> Vec<String> {
        messages
            .iter()
            .flat_map(|m| {
                let mut users = vec![m.author.clone()];
                if let Some(system) = &m.system {
                    match system {
                        SystemMessage::ChannelDescriptionChanged { by } => users.push(by.clone()),
                        SystemMessage::ChannelIconChanged { by } => users.push(by.clone()),
                        SystemMessage::ChannelOwnershipChanged { from, to, .. } => {
                            users.push(from.clone());
                            users.push(to.clone())
                        }
                        SystemMessage::ChannelRenamed { by, .. } => users.push(by.clone()),
                        SystemMessage::UserAdded { by, id, .. }
                        | SystemMessage::UserRemove { by, id, .. } => {
                            users.push(by.clone());
                            users.push(id.clone());
                        }
                        SystemMessage::UserBanned { id, .. }
                        | SystemMessage::UserKicked { id, .. }
                        | SystemMessage::UserJoined { id, .. }
                        | SystemMessage::UserLeft { id, .. } => {
                            users.push(id.clone());
                        }
                        SystemMessage::Text { .. } => {}
                        SystemMessage::MessagePinned { by, .. } => {
                            users.push(by.clone());
                        }
                        SystemMessage::MessageUnpinned { by, .. } => {
                            users.push(by.clone());
                        }
                        SystemMessage::CallStarted { by, .. } => users.push(by.clone()),
                        SystemMessage::ThreadCreated { by, .. } => users.push(by.clone()),
                        SystemMessage::CallRecordingStarted { by }
                        | SystemMessage::CallRecordingStopped { by } => users.push(by.clone()),
                    }
                }
                users
            })
            .collect::<HashSet<String>>()
            .into_iter()
            .collect::<Vec<String>>()
    }

    /// Helper function to fetch many messages with users
    pub async fn fetch_with_users(
        db: &Database,
        query: MessageQuery,
        perspective: &User,
        include_users: Option<bool>,
        server_id: Option<&str>,
    ) -> Result<BulkMessageResponse> {
        let messages = db.fetch_messages(query).await?;
        let user_ids = if let Some(true) = include_users {
            Some(Message::referenced_user_ids(&messages))
        } else {
            None
        };

        let messages: Vec<v0::Message> = messages
            .into_iter()
            .map(|msg| msg.into_model(None, None))
            .collect();

        if let Some(user_ids) = user_ids {
            let users = User::fetch_many_ids_as_mutuals(db, perspective, &user_ids).await?;

            Ok(BulkMessageResponse::MessagesAndUsers {
                messages,
                users,
                members: if let Some(server_id) = server_id {
                    Some(
                        db.fetch_members(server_id, &user_ids)
                            .await?
                            .into_iter()
                            .map(Into::into)
                            .collect(),
                    )
                } else {
                    None
                },
            })
        } else {
            Ok(BulkMessageResponse::JustMessages(messages))
        }
    }

    /// Append content to message
    pub async fn append(
        db: &Database,
        id: String,
        channel: String,
        append: AppendMessage,
    ) -> Result<()> {
        // Nothing to add, and nothing for clients to hear about.
        if append.embeds.as_ref().is_none_or(|v| v.is_empty()) {
            return Ok(());
        }

        // NotFound if the message was deleted meanwhile, so no event goes out for it.
        db.append_message(&id, &append).await?;

        EventV1::MessageAppend {
            id,
            channel: channel.to_string(),
            append: append.into(),
        }
        .p(channel)
        .await;

        Ok(())
    }

    /// Convert sendable embed to text embed and attach to message
    pub async fn attach_sendable_embed(
        &mut self,
        db: &Database,
        embed: v0::SendableEmbed,
    ) -> Result<()> {
        let media: Option<v0::File> = if let Some(id) = embed.media {
            Some(
                File::use_attachment(db, &id, &self.id, &self.author)
                    .await?
                    .into(),
            )
        } else {
            None
        };

        let embed = v0::Embed::Text(v0::Text {
            icon_url: embed.icon_url,
            url: embed.url,
            title: embed.title,
            description: embed.description,
            media,
            colour: embed.colour,
        });

        if let Some(embeds) = &mut self.embeds {
            embeds.push(embed);
        } else {
            self.embeds = Some(vec![embed]);
        }

        Ok(())
    }

    /// Add a reaction to a message
    pub async fn add_reaction(&self, db: &Database, user: &User, emoji: &str) -> Result<()> {
        // Check how many reactions are already on the message
        let config = config().await;
        if self.reactions.len() >= config.features.limits.global.message_reactions
            && !self.reactions.contains_key(emoji)
        {
            return Err(create_error!(InvalidOperation));
        }

        // Check if the emoji is whitelisted
        if !self.interactions.can_use(emoji) {
            return Err(create_error!(InvalidOperation));
        }

        // Check if the emoji is usable by us
        if !Emoji::can_use(db, emoji).await? {
            return Err(create_error!(InvalidOperation));
        }

        // Send reaction event
        EventV1::MessageReact {
            id: self.id.to_string(),
            channel_id: self.channel.to_string(),
            user_id: user.id.to_string(),
            emoji_id: emoji.to_string(),
        }
        .p(self.channel.to_string())
        .await;

        // Add emoji
        db.add_reaction(&self.id, emoji, &user.id).await
    }

    /// Validate the sum of content of a message is under threshold
    pub fn validate_sum(
        content: &Option<String>,
        embeds: &[SendableEmbed],
        max_length: usize,
    ) -> Result<()> {
        let mut running_total = 0;
        if let Some(content) = content {
            running_total += content.len();
        }

        for embed in embeds {
            if let Some(desc) = &embed.description {
                running_total += desc.len();
            }
        }

        if running_total <= max_length {
            Ok(())
        } else {
            Err(create_error!(PayloadTooLarge))
        }
    }

    /// Delete a message
    pub async fn delete(self, db: &Database) -> Result<()> {
        let mut file_ids: Vec<String> = self
            .attachments
            .map(|files| files.iter().map(|file| file.id.to_string()).collect())
            .unwrap_or_default();

        // Forward snapshots own their (freshly-minted) attachment copies —
        // they die with the forwarding message. Hash refcounting keeps the
        // underlying object alive for the original.
        if let Some(forwarded) = &self.forwarded {
            file_ids.extend(forwarded.attachments.iter().map(|file| file.id.to_string()));
        }

        if !file_ids.is_empty() {
            db.mark_attachments_as_deleted(&file_ids).await?;
        }

        // Cascade: a poll message takes its poll (and ballots) with it, so
        // the crond expiry scan can never publish PollClose for a deleted
        // message. Gated on the embedded definition to avoid a query on
        // every ordinary delete.
        if self.poll.is_some() {
            db.delete_polls_for_messages(std::slice::from_ref(&self.id))
                .await?;
        }

        // Cascade: a soft-res sheet message takes its sheet (and reserve
        // rows) with it. Gated on the embedded definition like polls.
        if self.softres.is_some() {
            db.delete_softres_for_messages(std::slice::from_ref(&self.id))
                .await?;
        }

        db.delete_message(&self.id).await?;

        EventV1::MessageDelete {
            id: self.id,
            channel: self.channel.clone(),
        }
        .p(self.channel)
        .await;
        Ok(())
    }

    /// Bulk delete messages
    pub async fn bulk_delete(db: &Database, channel: &str, ids: Vec<String>) -> Result<()> {
        let valid_ids = db
            .fetch_messages_by_id(&ids)
            .await?
            .into_iter()
            .filter(|msg| msg.channel == channel)
            .map(|msg| msg.id)
            .collect::<Vec<String>>();

        // Cascade before the messages go (single query for the whole batch).
        db.delete_polls_for_messages(&valid_ids).await?;
        db.delete_softres_for_messages(&valid_ids).await?;

        db.delete_messages(channel, &valid_ids).await?;
        EventV1::BulkMessageDelete {
            channel: channel.to_string(),
            ids: valid_ids,
        }
        .p(channel.to_string())
        .await;
        Ok(())
    }

    /// Bulk delete messages by an author since a given time
    pub async fn bulk_delete_by_author_since(
        db: &Database,
        channels: &[String],
        author: &str,
        since: SystemTime,
    ) -> Result<()> {
        let deleted_groups = db
            .delete_messages_by_author_since(channels, author, since)
            .await?;

        // Cascade: prune-deleted poll messages take their polls with them.
        let all_ids: Vec<String> = deleted_groups
            .iter()
            .flat_map(|(_, ids)| ids.iter().cloned())
            .collect();
        if !all_ids.is_empty() {
            db.delete_polls_for_messages(&all_ids).await?;
            db.delete_softres_for_messages(&all_ids).await?;
        }

        for (channel_id, message_ids) in deleted_groups {
            if !message_ids.is_empty() {
                EventV1::BulkMessageDelete {
                    channel: channel_id.clone(),
                    ids: message_ids,
                }
                .p(channel_id)
                .await;
            }
        }

        Ok(())
    }

    /// Remove a reaction from a message
    pub async fn remove_reaction(&self, db: &Database, user: &str, emoji: &str) -> Result<()> {
        // Check if it actually exists
        let empty = if let Some(users) = self.reactions.get(emoji) {
            if !users.contains(user) {
                return Err(create_error!(NotFound));
            }

            users.len() == 1
        } else {
            return Err(create_error!(NotFound));
        };

        // Send reaction event
        EventV1::MessageUnreact {
            id: self.id.to_string(),
            channel_id: self.channel.to_string(),
            user_id: user.to_string(),
            emoji_id: emoji.to_string(),
        }
        .p(self.channel.to_string())
        .await;

        if empty {
            // If empty, remove the reaction entirely
            db.clear_reaction(&self.id, emoji).await
        } else {
            // Otherwise only remove that one reaction
            db.remove_reaction(&self.id, emoji, user).await
        }
    }

    /// Remove a reaction from a message
    pub async fn clear_reaction(&self, db: &Database, emoji: &str) -> Result<()> {
        // Send reaction event
        EventV1::MessageRemoveReaction {
            id: self.id.to_string(),
            channel_id: self.channel.to_string(),
            emoji_id: emoji.to_string(),
        }
        .p(self.channel.to_string())
        .await;

        // Write to database
        db.clear_reaction(&self.id, emoji).await
    }

    pub fn remove_field(&mut self, field: &FieldsMessage) {
        match field {
            FieldsMessage::Pinned => self.pinned = None,
            FieldsMessage::Components => self.components = None,
        }
    }
}

/// Push recipients for a message in a thread: the thread's joined members and
/// any explicitly mentioned users, minus the author, restricted to users who
/// are still members of the server.
///
/// Thread membership rows can outlive server membership (a ban, kick or leave
/// does not necessarily remove them), and nothing downstream of the push queue
/// re-checks membership, so this filter is the gate that keeps removed users
/// from receiving message previews. A failed thread-member lookup is treated
/// as no joined members; a failed server-member lookup yields no recipients at
/// all (fail closed).
#[cfg_attr(not(feature = "tasks"), allow(dead_code))]
pub(crate) async fn thread_push_recipients(
    db: &Database,
    server_id: &str,
    thread_id: &str,
    author_id: &str,
    mentions: Option<&[String]>,
) -> Vec<String> {
    let mut candidates: Vec<String> = db
        .fetch_thread_members(thread_id)
        .await
        .unwrap_or_default()
        .into_iter()
        .map(|member| member.id.user)
        .filter(|uid| uid.as_str() != author_id)
        .collect();

    if let Some(mentions) = mentions {
        for uid in mentions {
            if uid.as_str() != author_id && !candidates.contains(uid) {
                candidates.push(uid.clone());
            }
        }
    }

    if candidates.is_empty() {
        return candidates;
    }

    let Ok(members) = db.fetch_members(server_id, &candidates).await else {
        return vec![];
    };

    let live: HashSet<String> = members.into_iter().map(|member| member.id.user).collect();
    candidates.retain(|uid| live.contains(uid));
    candidates
}

impl SystemMessage {
    pub fn into_message(self, channel: String) -> Message {
        Message {
            id: Ulid::new().to_string(),
            channel,
            author: "00000000000000000000000000".to_string(),
            system: Some(self),

            ..Default::default()
        }
    }
}

impl Interactions {
    /// Validate interactions info is correct
    pub async fn validate(&self, db: &Database, permissions: &PermissionValue) -> Result<()> {
        let config = config().await;

        if let Some(reactions) = &self.reactions {
            permissions.throw_if_lacking_channel_permission(ChannelPermission::React)?;

            if reactions.len() > config.features.limits.global.message_reactions {
                return Err(create_error!(InvalidOperation));
            }

            for reaction in reactions {
                if !Emoji::can_use(db, reaction).await? {
                    return Err(create_error!(InvalidOperation));
                }
            }
        }

        Ok(())
    }

    /// Check if we can use a given emoji to react
    pub fn can_use(&self, emoji: &str) -> bool {
        if self.restrict_reactions {
            if let Some(reactions) = &self.reactions {
                reactions.contains(emoji)
            } else {
                false
            }
        } else {
            true
        }
    }

    /// Check if default initialisation of fields
    pub fn is_default(&self) -> bool {
        !self.restrict_reactions && self.reactions.is_none()
    }
}

#[cfg(test)]
mod referenced_user_ids_tests {
    use super::*;

    fn message(author: &str, system: Option<SystemMessage>) -> Message {
        Message {
            id: Ulid::new().to_string(),
            channel: "channel".to_string(),
            author: author.to_string(),
            system,
            ..Default::default()
        }
    }

    fn sorted(mut ids: Vec<String>) -> Vec<String> {
        ids.sort();
        ids
    }

    #[test]
    fn authors_are_deduplicated() {
        let messages = vec![
            message("alice", None),
            message("bob", None),
            message("alice", None),
        ];

        assert_eq!(
            sorted(Message::referenced_user_ids(&messages)),
            vec!["alice".to_string(), "bob".to_string()]
        );
    }

    #[test]
    fn system_message_users_are_included_and_deduplicated() {
        let messages = vec![
            message("alice", None),
            message(
                "00000000000000000000000000",
                Some(SystemMessage::UserAdded {
                    id: "bob".to_string(),
                    by: "alice".to_string(),
                }),
            ),
            message(
                "00000000000000000000000000",
                Some(SystemMessage::ChannelOwnershipChanged {
                    from: "carol".to_string(),
                    to: "dave".to_string(),
                }),
            ),
            message(
                "00000000000000000000000000",
                Some(SystemMessage::Text {
                    content: "hello".to_string(),
                }),
            ),
        ];

        assert_eq!(
            sorted(Message::referenced_user_ids(&messages)),
            vec![
                "00000000000000000000000000".to_string(),
                "alice".to_string(),
                "bob".to_string(),
                "carol".to_string(),
                "dave".to_string(),
            ]
        );
    }

    /// Pins existing `fetch_with_users` behavior: the author id of a webhook
    /// message is the webhook id and is NOT filtered out here.
    #[test]
    fn webhook_author_id_is_kept() {
        let mut webhook_message = message("webhook", None);
        webhook_message.webhook = Some(MessageWebhook {
            name: "Hook".to_string(),
            avatar: None,
        });
        let messages = vec![message("alice", None), webhook_message];

        assert_eq!(
            sorted(Message::referenced_user_ids(&messages)),
            vec!["alice".to_string(), "webhook".to_string()]
        );
    }

    #[test]
    fn no_messages_no_ids() {
        assert!(Message::referenced_user_ids(&[]).is_empty());
    }
}

#[cfg(test)]
mod tests {
    use iso8601_timestamp::{Duration, Timestamp};

    use super::thread_push_recipients;
    use crate::{Channel, Database, Member, MemberCompositeKey};

    const SERVER: &str = "01TPRSERVER000000000000000";
    const THREAD: &str = "01TPRTHREAD000000000000000";
    const PARENT: &str = "01TPRPARENT000000000000000";
    const AUTHOR: &str = "01TPRAUTHOR000000000000000";
    const M1: &str = "01TPRMEMBER100000000000000";
    const M2: &str = "01TPRSTALE2000000000000000";
    const M3: &str = "01TPRMENTION30000000000000";
    const M4: &str = "01TPRMEMBER400000000000000";
    const M5: &str = "01TPRTIMEOUT50000000000000";

    #[allow(clippy::disallowed_methods)]
    async fn insert_thread(db: &Database, id: &str) {
        db.insert_channel(&Channel::Thread {
            id: id.to_string(),
            server: SERVER.to_string(),
            parent_channel: PARENT.to_string(),
            name: "thread".to_string(),
            creator: AUTHOR.to_string(),
            origin_message_id: None,
            last_message_id: None,
            archived: false,
            archived_timestamp: None,
            auto_archive_minutes: 0,
            locked: false,
            applied_tags: vec![],
        })
        .await
        .expect("insert thread");
    }

    async fn insert_member(db: &Database, user: &str, timeout: Option<Timestamp>) {
        db.insert_or_merge_member(&Member {
            id: MemberCompositeKey {
                server: SERVER.to_string(),
                user: user.to_string(),
            },
            timeout,
            ..Default::default()
        })
        .await
        .expect("insert member");
    }

    async fn join(db: &Database, user: &str) {
        db.join_thread_if_absent(THREAD, user)
            .await
            .expect("join thread");
    }

    #[tokio::test]
    async fn thread_push_recipients_excludes_non_members() {
        database_test!(|db| async move {
            insert_thread(&db, THREAD).await;

            // Server members: the author, M1 and M4. M2 and M3 are not.
            for user in [AUTHOR, M1, M4] {
                insert_member(&db, user, None).await;
            }

            // Joined rows: the author, M1, and M2's stale row from before
            // they were removed from the server.
            for user in [AUTHOR, M1, M2] {
                join(&db, user).await;
            }

            // M1 is mentioned as well as joined (no duplicate), the author
            // mentions themselves (excluded), M3 is a mentioned non-member.
            let mentions: Vec<String> = [M1, M3, AUTHOR, M4]
                .iter()
                .map(|id| id.to_string())
                .collect();

            let recipients =
                thread_push_recipients(&db, SERVER, THREAD, AUTHOR, Some(&mentions)).await;
            assert_eq!(
                recipients,
                vec![M1.to_string(), M4.to_string()],
                "thread push recipients must be the joined and mentioned users who are still server members"
            );

            // A member in timeout who is removed is only soft-deleted on
            // MongoDB (`pending_deletion_at`); the Reference driver panics on
            // that path, so this case runs on MongoDB only.
            if matches!(db, Database::MongoDb(_)) {
                insert_member(&db, M5, Some(Timestamp::now_utc() + Duration::minutes(5))).await;
                join(&db, M5).await;

                let before =
                    thread_push_recipients(&db, SERVER, THREAD, AUTHOR, Some(&mentions)).await;
                assert!(
                    before.iter().any(|id| id == M5),
                    "precondition: a live member in timeout is a recipient"
                );

                db.soft_delete_member(&MemberCompositeKey {
                    server: SERVER.to_string(),
                    user: M5.to_string(),
                })
                .await
                .expect("soft delete member");

                let after =
                    thread_push_recipients(&db, SERVER, THREAD, AUTHOR, Some(&mentions)).await;
                assert_eq!(
                    after,
                    vec![M1.to_string(), M4.to_string()],
                    "a soft-deleted (pending_deletion_at) member must not receive thread push"
                );
            }
        });
    }

    #[tokio::test]
    async fn thread_push_recipients_empty_without_rows_or_mentions() {
        database_test!(|db| async move {
            insert_thread(&db, THREAD).await;
            insert_member(&db, AUTHOR, None).await;

            assert!(
                thread_push_recipients(&db, SERVER, THREAD, AUTHOR, None)
                    .await
                    .is_empty(),
                "no joined rows and no mentions yields no recipients"
            );

            let self_mention = vec![AUTHOR.to_string()];
            assert!(
                thread_push_recipients(&db, SERVER, THREAD, AUTHOR, Some(&self_mention))
                    .await
                    .is_empty(),
                "an author mentioning themselves yields no recipients"
            );
        });
    }
}

#[cfg(all(test, feature = "tasks"))]
mod silent_flag_tests {
    use super::*;
    use crate::tasks::ack::{self, PushRoute};

    type Queued = (Option<PushNotification>, Message, Vec<String>, bool);

    #[test]
    fn suppress_notifications_is_mask_one_and_the_rest_are_bit_positions() {
        // Clients send `flags |= 1` for a silent message and read `flags & 1`.
        assert!(MessageFlagsValue(1).has(MessageFlags::SuppressNotifications));
        assert!(!MessageFlagsValue(2).has(MessageFlags::SuppressNotifications));

        let mut flags = MessageFlagsValue(0);
        flags
            .set(MessageFlags::SuppressNotifications, true)
            .set(MessageFlags::MentionsEveryone, true);
        assert_eq!(flags.0, 1 | 1 << 2);
        flags.set(MessageFlags::SuppressNotifications, false);
        assert_eq!(flags.0, 1 << 2);

        assert!(!MessageFlagsValue(1).has(MessageFlags::MentionsEveryone));
        assert!(MessageFlagsValue(1 << 5).has(MessageFlags::Interaction));
    }

    /// Send "hello" with request `flags` into a DM through `create_from_api`.
    /// Returns the stored message and the ack task entries the send queued.
    #[allow(clippy::disallowed_methods)]
    async fn send_dm(db: &Database, flags: Option<u32>) -> (Message, Vec<Queued>) {
        let author = User {
            id: Ulid::new().to_string(),
            username: "author".to_string(),
            discriminator: "0001".to_string(),
            ..Default::default()
        };
        let channel = Channel::DirectMessage {
            id: Ulid::new().to_string(),
            active: true,
            recipients: vec![author.id.clone(), Ulid::new().to_string()],
            last_message_id: None,
        };
        db.insert_channel(&channel).await.unwrap();

        // From JSON, as a request arrives, so new optional fields need no edit here.
        let data: DataMessageSend =
            serde_json::from_value(serde_json::json!({ "content": "hello", "flags": flags }))
                .unwrap();
        let model_author = author.clone().into_self(true).await;
        let message = Message::create_from_api(
            db,
            None,
            channel.clone(),
            data,
            MessageAuthor::User(&model_author),
            Some(model_author.clone()),
            None,
            author.limits().await,
            IdempotencyKey::unchecked_from_string(Ulid::new().to_string()),
            false,
            false,
        )
        .await
        .unwrap();

        (
            db.fetch_message(&message.id).await.unwrap(),
            ack::take_process_messages(channel.id()),
        )
    }

    #[tokio::test]
    #[allow(clippy::disallowed_methods)]
    async fn silent_send_is_marked_silenced_and_skips_push() {
        database_test!(|db| async move {
            let (stored, queued) = send_dm(&db, Some(1)).await;
            assert_eq!(stored.flags, Some(1));
            assert!(stored.has_suppressed_notifications());

            // Still queued, so the ack task records the DM unread, but
            // marked silenced, so it sends no push.
            let [(push, message, recipients, silenced)] = queued.as_slice() else {
                panic!("expected one queued ack entry, got {}", queued.len());
            };
            assert!(*silenced);
            assert_eq!(recipients.len(), 1);
            assert_eq!(
                ack::push_route(push.is_some(), message, recipients, *silenced),
                None
            );
        });
    }

    #[tokio::test]
    #[allow(clippy::disallowed_methods)]
    async fn plain_send_is_not_silenced_and_pushes() {
        database_test!(|db| async move {
            let (stored, queued) = send_dm(&db, None).await;
            assert!(!stored.has_suppressed_notifications());

            let [(push, message, recipients, silenced)] = queued.as_slice() else {
                panic!("expected one queued ack entry, got {}", queued.len());
            };
            assert!(!*silenced);
            assert_eq!(
                ack::push_route(push.is_some(), message, recipients, *silenced),
                Some(PushRoute {
                    direct: true,
                    mass_mention: false
                })
            );
        });
    }

    #[tokio::test]
    #[allow(clippy::disallowed_methods)]
    async fn request_flag_two_is_not_silent() {
        database_test!(|db| async move {
            // Bit 1 (value 2) was where the server used to look for
            // SuppressNotifications. It carries no flag now and is dropped.
            let (stored, queued) = send_dm(&db, Some(2)).await;
            assert_eq!(stored.flags, Some(0));
            assert!(!stored.has_suppressed_notifications());
            assert!(queued.iter().all(|(_, _, _, silenced)| !silenced));
        });
    }
}
